### PR TITLE
if type of returned value is None waitSecondTimesUrlResponseAttributeHasValue fails with exception

### PR DESCRIPTION
**Pull request by grigoryvasiliev**
it should continue to retry

### CODE REVIEW

**Comment by mikeplavsky** [comment]
i would really appreciate Acceptance Test, also please run Tests Suite - it was red

**Comment by grigoryvasiliev** [comment]
agree - will do

**Comment by mikeplavsky** [comment]
w/o fix 

image

**Comment by mikeplavsky** [comment]
with fix 

image

**Comment by mikeplavsky** [comment]
image

**Comment by mikeplavsky** [comment]
LGTM

**Pull request merged**
